version: '3.8'
services:
    app:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - db
            - redis
        env_file:
            - .env
    db:
        image: mysql:8.0
        restart: always
        env_file:
            - .env
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        ports:
            - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql

    redis:
        image: redis:alpine
        restart: always
        env_file:
            - .env
        ports:
            - "6380:6379"

volumes:
    db_data:
